theme: jekyll-theme-minimal
title: Ahmad Sofi Sidik
description: Website portofolio Ahmad Sofi Sidik, seorang software developer yang memiliki pengalaman dalam membuat aplikasi berbasis web dan mobile. serta memiliki antusias yang tinggi dalam teknologi khusus AI dan IoT.
